### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by VaibhavN1993** [gareth-sharpe/aplint-ext#2]
- Issue Type: `Bug`
- Extension Name: `sf-core-aplint-ext`
- Extension Version: `1.2.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by gareth-sharpe** [comment]
Not enough information.
